// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DLWCodeGeneratorExtensionNew
{
    internal sealed partial class Vsix
    {
        public const string Id = "DLWCodeGeneratorExtensionNew.908f4411-e54d-4896-8327-7b537ec9d2dc";
        public const string Name = "DLWCodeGeneratorExtensionNew";
        public const string Description = @"AI Toolset for X++ DevelopmentAI Toolset ";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Israilov, Musa";
        public const string Tags = "";
    }
}
